//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAdress { get; set; }
        public string SupplierZipCode { get; set; }
        public string SupplierCity { get; set; }
        public Nullable<decimal> SupplierLatitude { get; set; }
        public Nullable<decimal> SupplierLongitude { get; set; }
        public string SupplierPhoneNumber { get; set; }
        public string SupplierFax { get; set; }
        public Nullable<bool> SupplierIsTopPartner { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierWebSite { get; set; }
        public bool SupplierIsActive { get; set; }
        public Nullable<int> SupplierGeolocQuality { get; set; }
        public System.Data.Spatial.DbGeography SupplierGeographyPoint { get; set; }
        public int SupplierCountryId { get; set; }
        public int SupplierDistance { get; set; }
        public bool SupplierThreaded { get; set; }
        public string SupplierThreadedState { get; set; }
    }
}
